### ISSUE TITLE
all the food items are visible in every resturant

### ISSUE THREAD

**Issue by deepika-mahendra** [manjuies/Fooddo#2]
![Screenshot (499)](https://user-images.githubusercontent.com/59689415/88650606-7c9de700-d0e6-11ea-8c28-2a8a4ed23ebd.png)

**Comment by manjuies** [comment]
![bug4](https://user-images.githubusercontent.com/62104639/88653852-3ba7d180-d0ea-11ea-8ce8-48d4c21587aa.JPG)
Issue resolved
